"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <VINAY DEVARAKONDA> and <CESAR DAO CORADO>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: vd6965
UT EID 2: cad4837
"""


import sys
STEP_SIZE_CONSTANT = 3

def is_prime(n):
    """
    Determines if a number is prime.

    pre: n is a positive integer.
    post: Returns True if n is prime, otherwise returns False.
    """
    if n == 1:
        return False

    limit = int(n**0.5) + 1
    div = 2
    while div < limit:
        if n % div == 0:
            return False
        div += 1
    return True


def hash_word(s, size):
    """
    Hashes a lowercase string to an index in a hash table.

    pre: s is a lowercase string, and size is a positive integer representing either
         hash table size or the constant for double hashing.
    post: Returns an integer index in the range [0, size - 1] where the string hashes to.
    """
    hash_idx = 0
    for c in s:
        letter = ord(c) - 96
        hash_idx = (hash_idx * 26 + letter) % size
    return hash_idx


def step_size(s):
    """
    Calculates step size for double hashing using STEP_SIZE_CONSTANT.
    pre: s is a lowercase string.
    post: Returns the calculated step size as an integer based on the provided string.
    """
    return STEP_SIZE_CONSTANT - hash_word(s, STEP_SIZE_CONSTANT)




def insert_word(s, hash_table):
    """
    Inserts a string into the hash table using double hashing for collision resolution.
    No duplicates are allowed.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Inserts s into hash_table at the correct index; resolves any collisions
          by double hashing.
    """
    individual_step_size = step_size(s)
    next_index = hash_word(s, len(hash_table))
    while hash_table[next_index] != "" and hash_table[next_index] != s:
        next_index = (next_index + individual_step_size) % len(hash_table)

    hash_table[next_index] = s



def find_word(s, hash_table):
    """
    Searches for a string in the hash table.
    Note: using the `in` operator is incorrect as that will be O(N). We want
          an O(1) time average time complexity using hashing.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Returns True if s is found in hash_table, otherwise returns False.
    """
    individual_step_size = step_size(s)
    start_index = hash_word(s, len(hash_table))
    iterating_factor = start_index
    while hash_table[iterating_factor] != "":
        if hash_table[iterating_factor] == s:
            return True
        else:
            iterating_factor = (iterating_factor + individual_step_size) % len(hash_table)
    return False




def is_reducible(s, hash_table, hash_memo):
    """
    Determines if a string is reducible using a recursive check.

    pre: s is a lowercase string, hash_table is a list representing the hash table,
         and hash_memo is a list representing the hash table
         for memoization.
    post: Returns True if s is reducible (also updates hash_memo by
          inserting s if reducible), otherwise returns False.
    """
    vowel_cases = ['a', 'i', 'o']
    if not find_word(s, hash_table):
        return False
    if find_word(s, hash_memo):
        return True
    if len(s) == 1:
        if s in vowel_cases:
            return True
        else:
            return False
    if not ('a' in s or 'i' in s or 'o' in s):
        return False
    for i, _ in enumerate(s):
        temporary_remove = s[:i] + s[i+1:]
        if is_reducible(temporary_remove, hash_table, hash_memo):
            insert_word(s, hash_memo)
            return True
    return False

def get_longest_words(string_list):
    """
    Finds longest words from a list.

    pre: string_list is a list of lowercase strings.
    post: Returns a list of words in string_list that have the maximum length.
    """
    max_word_length = 0
    max_words_list = []
    for _, s in enumerate(string_list):
        if len(s) > max_word_length:
            max_word_length = len(s)
    for _, restring in enumerate(string_list):
        if len(restring) == max_word_length:
            max_words_list.append(restring)
    return max_words_list


def main():
    """The main function that calculates the longest reducible words"""
    strings = []
    for line in sys.stdin:
        strings.append(line.strip())
    word_list_len = len(strings)

    n = word_list_len * 2
    while not is_prime(n):
        n += 1
    hash_list = [""] * n
    for word in strings:
        insert_word(word, hash_list)

    m = int(word_list_len * 0.2)
    while not is_prime(m):
        m += 1
    hash_memo = [""] * m
    reducible_words = []
    for word in strings:
        if is_reducible(word, hash_list, hash_memo):
            reducible_words.append(word)
    long_red_word = get_longest_words(reducible_words)
    long_red_word.sort()
    for word in long_red_word:
        print(word)

if __name__ == "__main__":
    main()
